
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.naming.spi.DirStateFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * booktaxi.java
 *
 * Created on May 3, 2017, 12:07:38 PM
 */

/**
 *
 * @author PC-12
 */
public class Bookcab extends javax.swing.JFrame {

    /** Creates new form booktaxi */
    public Bookcab() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txt_pickup = new javax.swing.JTextField();
        txt_drop = new javax.swing.JTextField();
        txt_person = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        cmd_name = new javax.swing.JComboBox();
        cmd_taxiDetails = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Taxi");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 340, 70, 23);

        jButton3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 340, 80, 23);

        jButton4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 340, 70, 23);

        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 340, 70, 23);

        jButton8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton8.setText("|<First");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(107, 370, 70, 23);

        jButton5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton5.setText("<<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(190, 370, 50, 23);

        jButton6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton6.setText(">>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(250, 370, 50, 23);

        jButton7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton7.setText("Last>|");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(310, 370, 80, 23);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Pickup Point");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 140, 91, 21);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Booking Price (1 K.m)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 290, 150, 21);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Taxi Details ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 230, 84, 21);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Total Person");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 260, 120, 21);

        jLabel1.setFont(new java.awt.Font("Forte", 0, 48)); // NOI18N
        jLabel1.setText("Book Taxi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 220, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Drop Point");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 170, 77, 21);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Customer Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 200, 130, 21);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 45, 21);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Booking ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 91, 21);

        txt_ID.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_ID);
        txt_ID.setBounds(280, 80, 168, 20);

        txt_date.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_date);
        txt_date.setBounds(280, 110, 168, 20);

        txt_pickup.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_pickup);
        txt_pickup.setBounds(280, 140, 168, 20);

        txt_drop.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_drop);
        txt_drop.setBounds(280, 170, 168, 20);

        txt_person.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_person);
        txt_person.setBounds(280, 260, 168, 20);

        txt_price.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txt_price.setText("0");
        getContentPane().add(txt_price);
        txt_price.setBounds(280, 290, 168, 20);

        cmd_name.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cmd_name.setModel(new DefaultComboBoxModel());
        cmd_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_nameActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_name);
        cmd_name.setBounds(280, 200, 168, 20);

        cmd_taxiDetails.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cmd_taxiDetails.setModel(new DefaultComboBoxModel());
        cmd_taxiDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_taxiDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_taxiDetails);
        cmd_taxiDetails.setBounds(280, 230, 168, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-11\\Documents\\CBS\\Child_1.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-130, -70, 630, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
java.sql.Connection con=null;
java.sql.Statement stmt=null;
String dr="java.sql.Driver";
String url="jdbc:mysql://localhost:3306/cbs";
String pwd="a";
String usr="root";
String qry=" ";
ResultSet rs=null;
ResultSet rsCust=null;
ResultSet rsCab=null;
double amount=0;
double a=0;
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         
       try {
            rs.first();
            txt_ID.setText(rs.getInt("Book_id")+"");
            txt_date.setText(rs.getDate("book_dt")+"");
            txt_pickup.setText(rs.getString("pick_pnt")+"");
            txt_drop.setText(rs.getString("drop_pnt")+"");
            cmd_taxiDetails.setSelectedItem(rs.getString("TaxiID")+""); 
            cmd_name.setSelectedItem(rs.getString("Cust_nm")+""); 
            txt_person.setText(rs.getInt("totper")+"");
            txt_price.setText(rs.getInt("book_price")+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {

            rs.last();
            txt_ID.setText(rs.getInt("Book_id")+"");
            txt_date.setText(rs.getDate("book_dt")+"");
            txt_pickup.setText(rs.getString("pick_pnt")+"");
            txt_drop.setText(rs.getString("drop_pnt")+"");
            cmd_taxiDetails.setSelectedItem(rs.getString("TaxiID")+""); 
            
            cmd_name.setSelectedItem(rs.getString("cust_nm")+""); 
            
            txt_person.setText(rs.getInt("totper")+"");
            txt_price.setText(rs.getInt("book_price")+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {

            rs.previous();
            txt_ID.setText(rs.getInt("Book_id")+"");
            txt_date.setText(rs.getDate("book_dt")+"");
            txt_pickup.setText(rs.getString("pick_pnt")+"");
            txt_drop.setText(rs.getString("drop_pnt")+"");
            cmd_taxiDetails.setSelectedItem(rs.getString("TaxiID")+""); 
            cmd_name.setSelectedItem(rs.getString("Cust_nm")+""); 
            txt_person.setText(rs.getInt("totper")+"");
            txt_price.setText(rs.getInt("book_price")+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    try {

            rs.last();
            txt_ID.setText(rs.getInt("Book_id")+"");
            txt_date.setText(rs.getDate("book_dt")+"");
            txt_pickup.setText(rs.getString("pick_pnt")+"");
            txt_drop.setText(rs.getString("drop_pnt")+"");
            cmd_taxiDetails.setSelectedItem(rs.getString("TaxiID")+""); 
            cmd_name.setSelectedItem(rs.getString("Cust_nm")+""); 
            txt_person.setText(rs.getInt("totper")+"");
            txt_price.setText(rs.getInt("book_price")+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_ID.setText("");
        txt_date.setText("");
        txt_pickup.setText("");
        txt_drop.setText("");
        txt_person.setText("");
        txt_price.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
try {
                qry = "insert into BookTaxi values( "+txt_ID.getText()+",'"+txt_date.getText()+"','"+txt_pickup.getText()+"','"+txt_drop.getText()+"','"+cmd_name.getSelectedItem()+"','"+cmd_taxiDetails.getSelectedItem()+"','"+Integer.parseInt(txt_person.getText())+"',"+Integer.parseInt(txt_price.getText()) +")";
                stmt = con.createStatement();
                stmt.executeUpdate(qry);
                JOptionPane.showMessageDialog(rootPane, "Record Saved Sucessfully..........");
               } catch (Exception e) {
                  JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
              qry="delete from booktaxi where book_id="+txt_ID.getText();
              stmt=con.createStatement();
              stmt.executeUpdate(qry);

            JOptionPane.showMessageDialog(rootPane, "Record Delete successfully....!!!!!");

        } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, e);
            }       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.setBounds(400,150,522,510);

 
 try {
     Class.forName(dr);
     con = DriverManager.getConnection(url, usr, pwd);
     DefaultComboBoxModel cmd_mdl=(DefaultComboBoxModel)cmd_name.getModel(); 
     DefaultComboBoxModel cmd_mdl_2=(DefaultComboBoxModel)cmd_taxiDetails.getModel(); 
     
              qry= "select * from CustDetails";
             stmt=con.createStatement();
             rsCust=stmt.executeQuery(qry);
             while(rsCust.next())
             {
             cmd_mdl.addElement(rsCust.getString("Custnm"));
             }
             
             
                qry= "select * from CabDetails";
             stmt=con.createStatement();
             rsCab=stmt.executeQuery(qry);
             while(rsCab.next())
             {
             cmd_mdl_2.addElement(rsCab.getString("Cabmdl"));
             
             }
             
             
     qry= "select * from BookTaxi";
     stmt=con.createStatement();
     rs=stmt.executeQuery(qry);
                     
            rs.last();
            txt_ID.setText(rs.getInt("Book_id")+"");
            txt_date.setText(rs.getDate("book_dt")+"");
            txt_pickup.setText(rs.getString("pick_pnt")+"");
            txt_drop.setText(rs.getString("drop_pnt")+"");
            cmd_taxiDetails.setSelectedIndex(0); 
            
            txt_person.setText(rs.getInt("totper")+"");
            txt_price.setText(rs.getInt("book_price")+"");
           
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, e);
        }    
    }//GEN-LAST:event_formWindowOpened

    private void cmd_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_nameActionPerformed

    private void cmd_taxiDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_taxiDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_taxiDetailsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            qry="update booktaxi set book_dt ='"+txt_date.getText()+"',pick_pnt= '"+txt_pickup.getText()+"',drop_pnt= '"+txt_drop.getText()+"',cust_nm = 101,taxiID = 01, totper = "+Integer.parseInt(txt_price.getText())+" ,book_price = "+Integer.parseInt(txt_price.getText())+" where book_ID= "+Integer.parseInt(txt_ID.getText());
            stmt=con.createStatement();
            stmt.executeUpdate(qry);
             JOptionPane.showMessageDialog(rootPane, "Record Udated  successfully....!!!!!");

            } catch (Exception e) {
              JOptionPane.showMessageDialog(rootPane, e);

        }              // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookcab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmd_name;
    private javax.swing.JComboBox cmd_taxiDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_drop;
    private javax.swing.JTextField txt_person;
    private javax.swing.JTextField txt_pickup;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables

}
