
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FRM_CAB_DETAILS.java
 *
 * Created on May 3, 2017, 12:01:53 PM
 */

/**
 *
 * @author pcpc
 */
public class CabDetails extends javax.swing.JFrame {

    /** Creates new form FRM_CAB_DETAILS */
    public CabDetails() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_new = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txt_CabID = new javax.swing.JTextField();
        txt_CabNbr = new javax.swing.JTextField();
        txt_Mdl = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cab Details");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Cab ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 47, 18);

        jLabel1.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        jLabel1.setText("Cab Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 280, 56);

        btn_new.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        getContentPane().add(btn_new);
        btn_new.setBounds(60, 290, 80, 27);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setText("Capacity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 220, 60, 18);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Cab Driver");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 77, 18);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Model Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 160, 83, 18);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Cab Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 130, 88, 18);

        btn_save.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save);
        btn_save.setBounds(150, 290, 80, 27);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setText("Price(per km)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 250, 95, 18);

        jButton3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 290, 90, 27);

        jButton4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 290, 90, 27);

        jButton5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton5.setText("|<First");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 330, 80, 27);

        jButton6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(180, 330, 60, 27);

        jButton7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton7.setText(">>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(250, 330, 60, 27);

        jButton8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton8.setText("Last>|");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(320, 330, 80, 27);

        txt_CabID.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        getContentPane().add(txt_CabID);
        txt_CabID.setBounds(260, 100, 140, 24);

        txt_CabNbr.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        getContentPane().add(txt_CabNbr);
        txt_CabNbr.setBounds(260, 130, 140, 24);

        txt_Mdl.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txt_Mdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MdlActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Mdl);
        txt_Mdl.setBounds(260, 160, 140, 24);

        t5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        getContentPane().add(t5);
        t5.setBounds(260, 220, 140, 24);

        t6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        getContentPane().add(t6);
        t6.setBounds(260, 250, 140, 24);

        t4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(260, 190, 140, 24);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-11\\Documents\\CBS\\Child_1.jpg")); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-70, -100, 620, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents
java.sql.Connection con=null;
Statement stmt=null;
String dr="java.sql.Driver";
String  url="jdbc:mysql://localhost:3306/CBS";
String usr="root";
String pwd="a";
String qry="";
ResultSet rs=null;
    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
try {
    

    txt_CabID.setText("");
    txt_CabNbr.setText("");
    txt_Mdl.setText("");
    t5.setText("");
    t6.setText("");
    t4.setText("");


        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);

        }
}//GEN-LAST:event_btn_newActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
          try {
                qry = "insert into CabDetails values( "+txt_CabID.getText()+",'"+txt_CabNbr.getText()+"','"+txt_Mdl.getText()+"','"+t4.getText()+"','"+t5.getText()+"',"+t6.getText() +")";
                stmt = con.createStatement();
                stmt.executeUpdate(qry);
                JOptionPane.showMessageDialog(rootPane, "Record Saved Sucessfully");
               } catch (Exception e) {
                  JOptionPane.showMessageDialog(rootPane, e);

        }
}//GEN-LAST:event_btn_saveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            qry="update cabdetails set  CabNbr='"+txt_CabNbr.getText()+"',CabMdl='"+txt_Mdl.getText()+"',CabDriverNm='"+t4.getText()+"',CabCpcty='"+t5.getText()+"', CabPrice="+t6.getText()+" where CabID="+txt_CabID.getText();
            stmt=con.createStatement();
            stmt.executeUpdate(qry);
            
            JOptionPane.showMessageDialog(rootPane,"RECORDS UPDATED SUCCESSFULLY!!!!!!!!");
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
             qry="delete from cabdetails where CabID = "+txt_CabID.getText();
            stmt=con.createStatement();
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane,"RECORDS DELETED SUCCESSFULLY!!!!!!!!");
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
             qry= "select * from cabDetails";
             stmt=con.createStatement();
             rs=stmt.executeQuery(qry);
               
               rs.first();
                txt_CabID.setText(""+rs.getInt("CabId"));
                txt_CabNbr.setText(""+rs.getString("CabNbr"));
                txt_Mdl.setText(""+rs.getString("CabMdl"));
                t4.setText(""+rs.getString("CabDriverNm"));
                t5.setText(""+rs.getInt("CabCpcty"));
                t6.setText(""+rs.getInt("Cabprice"));
            
             
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            rs.previous();
             txt_CabID.setText(""+rs.getInt("CabId"));
             txt_CabNbr.setText(""+rs.getString("CabNbr"));
             txt_Mdl.setText(""+rs.getString("CabMdl"));
             t4.setText(""+rs.getString("CabDriverNm"));
             t5.setText(""+rs.getInt("CabCpcty"));
             t6.setText(""+rs.getInt("Cabprice"));
            
             } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            rs.next();
            txt_CabID.setText(""+rs.getInt("CabId"));
            txt_CabNbr.setText(""+rs.getString("CabNbr"));
            txt_Mdl.setText(""+rs.getString("CabMdl"));
            t4.setText(""+rs.getString("CabDriverNm"));
            t5.setText(""+rs.getInt("CabCpcty"));
            t6.setText(""+rs.getInt("Cabprice"));
            
            } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       try {
           
            rs.last();
            txt_CabID.setText(""+rs.getInt("CabId"));
            txt_CabNbr.setText(""+rs.getString("CabNbr"));
            txt_Mdl.setText(""+rs.getString("CabMdl"));
            t4.setText(""+rs.getString("CabDriverNm"));
            t5.setText(""+rs.getInt("CabCpcty"));
            t6.setText(""+rs.getInt("Cabprice"));
            
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txt_MdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MdlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MdlActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       this.setBounds(300, 150, 565, 470);
      
       
       try {
              Class.forName(dr);
              con=DriverManager.getConnection(url, usr, pwd);
              qry= "select * from cabDetails";
              stmt=con.createStatement();
              rs=stmt.executeQuery(qry);
            
              rs.last();
               txt_CabID.setText(""+rs.getInt("CabId"));
               txt_CabNbr.setText(""+rs.getString("CabNbr"));
               txt_Mdl.setText(""+rs.getString("CabMdl"));
               t4.setText(""+rs.getString("CabDriverNm"));
               t5.setText(""+rs.getString("CabCpcty"));
               t6.setText(""+rs.getInt("Cabprice"));
            
             
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CabDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField txt_CabID;
    private javax.swing.JTextField txt_CabNbr;
    private javax.swing.JTextField txt_Mdl;
    // End of variables declaration//GEN-END:variables

}
