
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustDetails.java
 *
 * Created on May 3, 2017, 11:59:56 AM
 */

/**
 *
 * @author PC-12
 */
public class CustDetails extends javax.swing.JFrame {

    /** Creates new form CustDetails */
    public CustDetails() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_CustID = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_Add = new javax.swing.JTextField();
        txt_ContNm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Details");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton7.setText("Last>|");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(250, 260, 70, 23);

        jButton4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 230, 80, 23);

        jButton3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 230, 80, 23);

        jButton6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton6.setText(">>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(180, 260, 60, 23);

        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 230, 70, 23);

        jButton5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton5.setText("<<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(110, 260, 60, 23);

        jButton8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton8.setText("|<First");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(33, 260, 70, 23);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 230, 60, 23);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Contact No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 78, 21);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 78, 21);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 45, 21);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 45, 21);

        txt_CustID.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_CustID);
        txt_CustID.setBounds(150, 90, 203, 20);

        txt_Name.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_Name);
        txt_Name.setBounds(150, 120, 203, 20);

        txt_Add.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_Add);
        txt_Add.setBounds(150, 150, 203, 20);

        txt_ContNm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        getContentPane().add(txt_ContNm);
        txt_ContNm.setBounds(150, 180, 203, 20);

        jLabel1.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel1.setText("Customer Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 270, 37);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-11\\Documents\\CBS\\Child_2.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 410, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents
java.sql.Connection con=null;
java.sql.Statement stmt=null;
String dr="java.sql.Driver";
String url="jdbc:mysql://localhost:3306/cbs";
String pwd="a";
String usr="root";
String qry=" ";
ResultSet rs=null;
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
   try {

            rs.first();
                txt_CustID.setText(rs.getInt("CustID")+"");
                txt_Name.setText(rs.getString("Custnm")+"");
                txt_Add.setText(rs.getString("CustAddr")+"");
                txt_ContNm.setText(rs.getString("Custcnt")+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {

            rs.last();
                txt_CustID.setText(rs.getInt("CustID")+"");
                txt_Name.setText(rs.getString("Custnm")+"");
                txt_Add.setText(rs.getString("CustAddr")+"");
                txt_ContNm.setText(rs.getString("Custcnt")+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {

            rs.next();
                txt_CustID.setText(rs.getInt("CustID")+"");
                txt_Name.setText(rs.getString("Custnm")+"");
                txt_Add.setText(rs.getString("CustAddr")+"");
                txt_ContNm.setText(rs.getString("Custcnt")+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
             rs.previous();
                txt_CustID.setText(rs.getInt("CustID")+"");
                txt_Name.setText(rs.getString("Custnm")+"");
                txt_Add.setText(rs.getString("CustAddr")+"");
                txt_ContNm.setText(rs.getString("Custcnt")+"");
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        txt_CustID.setText("");        
        txt_Name.setText("");
        txt_Add.setText("");
        txt_ContNm.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try {
            qry="insert into CustDetails values( "+txt_CustID.getText()+",'"+txt_Name.getText()+"' ,'"+txt_Add.getText()+"','"+txt_ContNm.getText()+"')";
            stmt=con.createStatement();
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane, "Record Saved Successfully....!!!!!");

            
              qry= "select * from CustDetails";
              stmt=con.createStatement();
              rs=stmt.executeQuery(qry);
     
         } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, e);

        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
            qry="update CustDetails set  Custnm='"+txt_Name.getText()+"', CustAddr= '"+txt_Add.getText()+"'  ,Custcnt= '"+txt_ContNm.getText()+"'where CustID= "+txt_CustID.getText();
            stmt=con.createStatement();
            stmt.executeUpdate(qry);
             JOptionPane.showMessageDialog(rootPane, "Record Udated  successfully....!!!!!");

            } catch (Exception e) {
              JOptionPane.showMessageDialog(rootPane, e);

        }      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         try {
              qry="delete from CustDetails where custid="+txt_CustID.getText();
              stmt=con.createStatement();
              stmt.executeUpdate(qry);

            JOptionPane.showMessageDialog(rootPane, "Record Delete successfully....!!!!!");

        } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, e);
            }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         this.setBounds(200,150,417,382);  
        try {
             Class.forName(dr);
              con=DriverManager.getConnection(url, usr, pwd);
              qry= "select * from CustDetails";
              stmt=con.createStatement();
              rs=stmt.executeQuery(qry);
            
              rs.last();
                txt_CustID.setText(rs.getInt("CustID")+"");
                txt_Name.setText(rs.getString("Custnm")+"");
                txt_Add.setText(rs.getString("CustAddr")+"");
                txt_ContNm.setText(rs.getString("Custcnt")+"");
               }
          catch (Exception e)
          {
          JOptionPane.showConfirmDialog(rootPane, e);
          }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_Add;
    private javax.swing.JTextField txt_ContNm;
    private javax.swing.JTextField txt_CustID;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables

}
