
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmcabdetaillsearch.java
 *
 * Created on May 10, 2017, 11:54:55 AM
 */

/**
 *
 * @author PC-12
 */
public class frmbooking extends javax.swing.JFrame {

    /** Creates new form frmcabdetaillsearch */
    public frmbooking() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_data = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Booking");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        cmd.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cmd.setModel(new DefaultComboBoxModel());
        getContentPane().add(cmd);
        cmd.setBounds(400, 80, 159, 20);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("Go....!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 80, 80, 23);

        table_data.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        table_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking Date", "PickUp Point", "Drop Point", "CustDetails", "Taxi ID", "Book Price", "Discount Price"
            }
        ));
        table_data.setOpaque(false);
        jScrollPane1.setViewportView(table_data);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 1012, 92);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Select Booking Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 80, 150, 17);

        jLabel1.setFont(new java.awt.Font("Forte", 2, 48)); // NOI18N
        jLabel1.setText("Search Booking");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 330, 60);

        jLabel2.setDisplayedMnemonic('S');
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-11\\Documents\\CBS\\Child_3.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-80, -180, 1180, 490);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 80, 34, 14);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 80, 190, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
java.sql.Connection con=null;
java.sql.Statement stmt=null;
String dr="java.sql.Driver";
String url="jdbc:mysql://localhost:3306/cbs";
String pwd="a";
String usr="root";
String qry="";
ResultSet rs=null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            qry="select * from BookTaxi where book_dt='"+cmd.getSelectedItem()+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(qry);
             DefaultTableModel tbl_mdl=(DefaultTableModel)table_data.getModel();
           
            tbl_mdl.setRowCount(0);
            while(rs.next()) {
                tbl_mdl.addRow(new Object[]{rs.getInt("book_id"),rs.getDate("book_dt"),rs.getString("Pick_pnt"),rs.getString("Drop_pnt"),rs.getString("Cust_nm"),rs.getString("TaxiID"),rs.getInt("Totper"),rs.getDouble("book_price")});
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       this.setBounds(100, 150, 1040, 346);
        try {
            Class.forName(dr);
            con=DriverManager.getConnection(url, usr, pwd);
            DefaultComboBoxModel cmd_mdl=(DefaultComboBoxModel)cmd.getModel();
            
            qry="select distinct book_dt from BookTaxi ";
            stmt=con.createStatement();
            rs=stmt.executeQuery(qry);
              while(rs.next()) {
                  cmd_mdl.addElement(rs.getString("book_dt"+""));
              }
            
            
            
            qry="select * from BookTaxi ";
            stmt=con.createStatement();
            rs=stmt.executeQuery(qry);
             DefaultTableModel tbl_mdl=(DefaultTableModel)table_data.getModel();
           
            while(rs.next()) {
            tbl_mdl.addRow(new Object[]{rs.getDate("book_dt"),rs.getString("Pick_pnt"),rs.getString("Drop_pnt"),rs.getString("Cust_nm"),rs.getString("TaxiID"),rs.getInt("Totper"),rs.getDouble("book_price")});
          }


        } catch (Exception e) {
        } // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_data;
    // End of variables declaration//GEN-END:variables

}
