
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmcabdetailssearch1.java
 *
 * Created on May 10, 2017, 12:02:24 PM
 */

/**
 *
 * @author PC-12
 */
public class frmcabdetailssearch1 extends javax.swing.JFrame {

    /** Creates new form frmcabdetailssearch1 */
    public frmcabdetailssearch1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Cab");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        getContentPane().add(cmd);
        cmd.setBounds(354, 93, 159, 20);

        tbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cab Model", "Cab Driver Name", "Cab Capacity", "Price (1 KM)"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(26, 133, 803, 92);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Go....!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 90, 100, 25);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Select Cab Model");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(173, 94, 123, 17);

        jLabel2.setFont(new java.awt.Font("Forte", 2, 48)); // NOI18N
        jLabel2.setText("Search Cab");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 20, 240, 60);

        jLabel3.setDisplayedMnemonic('t');
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-11\\Documents\\CBS\\Child_3.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-190, -180, 1110, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents
java.sql.Connection con=null;
java.sql.Statement stmt=null;
String dr="java.sql.Driver";
String url="jdbc:mysql://localhost:3306/CBS";
String pwd="a";
String usr="root";
String qry="";
ResultSet rs=null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
          Class.forName(dr);
            con=DriverManager.getConnection(url, usr, pwd);
            qry="select * from cabdetails where cabNbr='"+cmd.getSelectedItem()+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(qry);
            DefaultTableModel tbl_mdl=(DefaultTableModel)tbl.getModel();
           tbl_mdl.setRowCount(0);
            while(rs.next()) {
            tbl_mdl.addRow(new Object[]{rs.getString("CabNbr"),rs.getString("CabDriverNm"),rs.getString("Cabcpcty"),rs.getInt("CabPrice")});
              }


        } catch (Exception e) {
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 this.setBounds(100, 150, 925, 340);
 
        
        try {
            Class.forName(dr);
            con=DriverManager.getConnection(url, usr, pwd);
       DefaultComboBoxModel cmd_mdl=(DefaultComboBoxModel)cmd.getModel();
            
            DefaultTableModel tbl_mdl=(DefaultTableModel)tbl.getModel();
           
            qry="select * from Cabdetails ";
            stmt=con.createStatement();
            rs=stmt.executeQuery(qry);
            
            while(rs.next()) {
            cmd_mdl.addElement(rs.getString("CabNBr"+""));
            tbl_mdl.addRow(new Object[]{rs.getString("CabNbr"),rs.getString("CabDriverNm"),rs.getString("Cabcpcty"),rs.getInt("CabPrice")});
            }


        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcabdetailssearch1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

}
