
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmcustsearch.java
 *
 * Created on May 10, 2017, 11:49:51 AM
 */

/**
 *
 * @author PC-12
 */
public class frmcustsearch extends javax.swing.JFrame {

    /** Creates new form frmcustsearch */
    public frmcustsearch() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        cmd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(cmd);
        cmd.setBounds(180, 100, 159, 21);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Go....!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 100, 71, 23);

        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "Customer Address", "Customer Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 452, 92);

        jLabel1.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel1.setText("Search Customer Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 380, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Select Customer Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 130, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-11\\Documents\\CBS\\Child_3.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-570, -170, 1110, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents
java.sql.Connection con=null;
java.sql.Statement stmt=null;
String dr="java.sql.Driver";
String url="jdbc:mysql://localhost:3306/cbs";
String pwd="a";
String usr="root";
String qry="";
ResultSet rs=null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            Class.forName(dr);
            con=DriverManager.getConnection(url, usr, pwd);
        DefaultComboBoxModel cmd_mdl=(DefaultComboBoxModel)cmd.getModel();
        qry="select * from custdetails where CustID='"+cmd.getSelectedItem()+"'";
        stmt=con.createStatement();
        rs=stmt.executeQuery(qry);
        DefaultTableModel tbl_mdl=(DefaultTableModel)jTable1.getModel();
        tbl_mdl.setRowCount(0);
        while(rs.next())
        {
            tbl_mdl.addRow(new Object[]{rs.getInt("CustID"),rs.getString("Custnm"),rs.getString("CustAddr"),rs.getString("Custcnt")});
        }


        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.setBounds(100, 150, 550, 360);
        
        try {
            Class.forName(dr);
            con=DriverManager.getConnection(url, usr, pwd);
            DefaultComboBoxModel cmd_mdl=(DefaultComboBoxModel)cmd.getModel();
            qry="select * from Custdetails ";
            stmt=con.createStatement();
            rs=stmt.executeQuery(qry);
            DefaultTableModel tbl_mdl=(DefaultTableModel)jTable1.getModel();
        
            while(rs.next()) {
            cmd_mdl.addElement(rs.getInt("CustID"+""));
           tbl_mdl.addRow(new Object[]{rs.getInt("CustID"),rs.getString("Custnm"),rs.getString("CustAddr"),rs.getString("Custcnt")});
     
            }


        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcustsearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
